[versions]
atrium = "1.1.0"
junitJupiter = "5.10.1"

[libraries]
atrium-fluent = { module = "ch.tutteli.atrium:atrium-fluent", version.ref = "atrium" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
